# Learn more → https://github.com/TryGhost/action-deploy-theme#getting-started
name: Deploy Theme
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@v1
        with:
          api-url: ${{'https://ichigendo.ghost.io'}}
          api-key: ${{'663e7595a650ff00018472f8:3fa189b575ebe49b161098b100f7c7f371e8984f3b376db109ef6a315c6b3676'}}
